### ISSUE TITLE
Runtime Error: "Invalid duration specification for t"

### ISSUE THREAD

**Issue by jeromepl** [enzanki-ars/rocket-league-minimap-generator#44] opened 2018-01-13 02:23 UTC
With the new v1.4.0-alpha version, I run into a new issue when trying to run this project (no matter whether I run it from the `.exe` or through python). Here is the exact error message:
```
Invalid duration specification for t: 7.759126674500294e-12
```

And here is the complete log along with the json replay file I was using. Note that it says render was completed but no video file is created in the `renders` folder.
```
PS D:\User\Dropbox\programming\rocket-league-replay-analysis> .\rocketleaguereplayanalysis.exe --render=scoreboard .\tes
t\B577BBD84F3B59209DA62D916392E14E.json
Parsing data...
Data successfully parsed.
Rendering video...
FFmpeg Command: ['ffmpeg', '-loop', '1', '-i', 'D:\\Temp\\_MEI70762\\assets\\scoreboard.png', '-t', '7.759126674500294e-12', '-vf', "sendcmd=f=frames-frame_num-time-game_minutes.txt,drawtext@frames-frame_num-time-game_minutes=fontfile=\\'D:\\\\Temp\\\\_MEI70762\\\\assets\\\\OpenSans.ttf\\':fontsize=24:fontcolor=black:x=6:y=45:text=00:expansion=none,sendcmd=f=frames-frame_num-time-game_seconds.txt,drawtext@frames-frame_num-time-game_seconds=fontfile=\\'D:\\\\Temp\\\\_MEI70762\\\\assets\\\\OpenSans.ttf\\':fontsize=24:fontcolor=black:x=41:y=45:text=00:expansion=none,sendcmd=f=team_info-color-team0.txt,drawbox@team_info-color-team0=color=0x7f7fff:x=74:y=2:h=34:w=142:thickness=fill,sendcmd=f=team_info-color-team1.txt,drawbox@team_info-color-team1=color=0xffb27f:x=74:y=38:h=34:w=142:thickness=fill,sendcmd=f=team_info-name-team0.txt,drawtext@team_info-name-team0=fontfile=\\'D:\\\\Temp\\\\_MEI70762\\\\assets\\\\OpenSans.ttf\\':text=Blue:fontsize=24:fontcolor=black:x=80:y=10:expansion=none,sendcmd=f=team_info-name-team1.txt,drawtext@team_info-name-team1=fontfile=\\'D:\\\\Temp\\\\_MEI70762\\\\assets\\\\OpenSans.ttf\\':text=Orange:fontsize=24:fontcolor=black:x=80:y=45:expansion=none,sendcmd=f=frames-frame_num-scoreboard-team0.txt,drawtext@frames-frame_num-scoreboard-team0=fontfile=\\'D:\\\\Temp\\\\_MEI70762\\\\assets\\\\OpenSans.ttf\\':fontsize=24:fontcolor=black:x=225:y=10:expansion=none:text=0,sendcmd=f=frames-frame_num-scoreboard-team1.txt,drawtext@frames-frame_num-scoreboard-team1=fontfile=\\'D:\\\\Temp\\\\_MEI70762\\\\assets\\\\OpenSans.ttf\\':fontsize=24:fontcolor=black:x=225:y=45:expansion=none:text=0", '-r', '30', 'scoreboard.mp4', '-y']
ffmpeg version N-89674-g57d0c24132 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  3.100 / 58.  3.100
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  8.100 /  7.  8.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, png_pipe, from 'D:\Temp\_MEI70762\assets\scoreboard.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 290x74 [SAR 3779:3779 DAR 145:37], 25 fps, 25 tbr, 25 tbn, 25 tbc
Invalid duration specification for t: 7.759126674500294e-12
Render completed.
```

[test.zip](https://github.com/enzanki-ars/rocket-league-replay-analysis/files/1627969/test.zip)

**Comment by enzanki-ars** [comment] 2018-01-13 02:49
That is weird.  Looking into it.  It seems that it thinks that the replay is only 0.000000000007759126674500294 seconds long....

**Comment by enzanki-ars** [comment] 2018-01-13 02:58
See the problem:

```
replay_time | server_time | replay_delta | server_delta | real_replay_time | real_replay_delta
0.013895    | 3.51467729  | 0.006948     | -362.3294227 | -362.329         | -362.329
```

Those should not be negative...  Fixing the issue now.  Sorry you have had so much trouble with the program... I don't have many replay files to test with, and there are some weird replays out there depending on the OS the game was played on...

**Comment by enzanki-ars** [comment] 2018-01-13 03:04
Source of the problem: `server_delta` was calculated for frame 0, which it shouldn't have been.  The code to calculate `server_delta`: `data['Frames'][i]['Time'] - data['Frames'][i - 1]['Time']`, with would end up being `first_frame_time - last_frame_time`.  I wonder how any of my replay files have worked at all...

**Comment by jeromepl** [comment] 2018-01-13 03:09
No worries, I am here to help! On that note, I should contact you soon on Reddit to discuss some ideas I had for this project.

**Comment by enzanki-ars** [comment] 2018-01-13 03:12
Issue should be fixed, and I will upload a fixed exe.  Just a quick question: the replay you sent me ends after the 9th goal with 30 seconds left on the game clock.  I just want to make sure, is this as intended?

**Comment by enzanki-ars** [comment] 2018-01-13 03:13
Feel free to contact me on Reddit at /u/enzanki_ars.

**Comment by jeromepl** [comment] 2018-01-13 03:17
Just checked in Rocket League and yes indeed this game ends after the 9th goal with 30s left!

**Comment by jeromepl** [comment] 2018-01-13 03:24
I successfully ran rocketleaguereplayanalysis on this replay without any issues. Your fix seems to have done the trick!

**Closed as completed** 2018-01-13 03:24 UTC

**Comment by enzanki-ars** [comment] 2018-01-13 03:26
Was just about to send you the info for the latest compiled version, but I'm glad to see that you were able to run the program yourself in python without any issues, compared to the previous releases....

I do want to let you know that boost values are incorrect at the moment.  Documenting that soon as an issue here, but it is noted now at https://github.com/enzanki-ars/rocket-league-replay-analysis/releases
